language: python
python:
  - "2.7"
install:
  - "pip install -r requirements/test.txt --use-mirrors"
  - pip install coveralls
script:
  - coverage run batter/manage.py test --settings=batter.settings.test
  - flake8 --select=E,W batter --exclude="migrations"
after_success:
  - coveralls
