language: python
python:
  - "2.7"
install:
  - pip install -r requirements/test.txt --index-url=https://simple.crate.io
  - pip install coveralls --index-url=https://simple.crate.io
script:
  - coverage run batter/manage.py test --settings=batter.settings.test
  - flake8 --select=E,W batter --exclude="migrations"
after_success:
  - coveralls
notifications:
  webhooks:
    urls:
      - http://batterbetterbotter.herokuapp.com/hubot/travis/?room=%23batter,batter
    on_success: always
    on_failure: always
    on_start: true
