language: python
python:
  - "2.7"
install:
  - "pip install -r requirements/test.txt --use-mirrors"
script:
  - coverage run batter/manage.py test --settings=batter.settings.test
  - coverage html --include "batter/*" --omit="admin.py,site-packages"
